from rest_framework.decorators import api_view
from rest_framework.response import Response

from .utils import get_route
from .hos import generate_logs
from .models import Trip


@api_view(["POST"])
def plan_trip(request):

    start = request.data["start"]
    end = request.data["end"]
    cycle = request.data["cycle"]

    miles,polyline = get_route(start,end)
    logs = generate_logs(miles,cycle)

    Trip.objects.create(
        start_lat=start["lat"],
        start_lng=start["lng"],
        end_lat=end["lat"],
        end_lng=end["lng"],
        total_miles=miles
    )

    return Response({
        "total_miles":round(miles,2),
        "logs":logs,
        "polyline":polyline,
        "start":start,
        "end":end
    })


from reportlab.pdfgen import canvas
from django.http import HttpResponse


@api_view(["GET"])
def export_pdf(request):

    response=HttpResponse(content_type='application/pdf')
    response['Content-Disposition']='attachment; filename="logs.pdf"'

    p=canvas.Canvas(response)

    p.drawString(100,800,"HOS LOG REPORT")

    p.drawString(100,770,"Generated by HOS Planner")

    p.save()

    return response
